import classNames from "classnames/bind";
import styles from "../../styles/CreatePost.module.scss";
const cx = classNames.bind(styles);

import Head from "next/head";
import { useRouter } from "next/router";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import BreadcrumbLayout from "../../components/Layout/BreadcrumbLayout";
import useBreadcrumbs from "../../hooks/useBreadcrumbs";
import { useRef, useState, useEffect, ChangeEvent } from "react";



export interface CreatePostProps {}
const CreatePost = () => {
    const router = useRouter();
    const newRouter = useBreadcrumbs(router);

    const eventSendMessage = () => {
        // console.log(editorState)
    };

    return (
        <div>
            <Head>
                <title>Create Post - HoBa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Header />
                <div className={cx("wrapper")}>
                    <div className={cx("container")}>

                        <div className={cx("writting")}>
                            {/* <div dangerouslySetInnerHTML={{__html: data}}></div> */}
                        </div>


                    </div>
                </div>
                <Footer />
            </main>
        </div>
    );
};

export default CreatePost;
